/**
 * 
 * Given two strings, s and t, comprising only lowercase letters,
 * t is generated by shuffling the letters in s as well as 
 * potentially adding an additional random number. Return the
 * number that was randomly added to t if it exists, otherwise,
 * return ' '.
 * Note: Assumption - At most one additional character can be added to t.
 * 
 * Ex: Given the following strings...
 * 
 * s = "foobar", t = "barfoot", return 't'
 * s = "ide", t = "idea", return 'a'
 * s = "coding", t "ingcod", return ""
 * 
 */


function spot(s,t){
    var diff = ''
    var sSorted = s.split('').sort().join()
    var tSorted = t.split('').sort().join()
    for (let i of tSorted){
        var set = new Set(sSorted);
        if (!set.has(i)){
            diff += i
        }
    } 
    return diff;
}


console.log(spot("foobar", "barfoot"))
console.log(spot("ide", "idea"))
console.log(spot("coding", "ingcod"))
